[package]
name = "sonatina-ir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.10"
cranelift-entity = "0.77"
smallvec = "1.7.0"
fxhash = "0.2.1"
dyn-clone = "1.0.4"
sonatina-triple = { path = "../triple" }
indexmap = "1.9.1"
