[package]
name = "sonatina-frontend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift-entity = "0.77"

sonatina-codegen = { path = "../codegen", version = "0.1.0" }
