[package]
name = "sonatina-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.10"
cranelift-entity = "0.77"
smallvec = "1.7.0"
